# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mattie Tesfaldet
email: tesfaldet@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mtesfaldet.net" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-74037692-3

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

defaults:
  - scope:
      path: "news/_posts"
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "news_post"
  - scope:
      path: "pubs/_posts"
      type: "posts"
    values:
      layout: "pub_post"
  - scope:
      path: "pubs"
      type: "pages"
    values:
      layout: "pub_page"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/vid"
    values:
      video: true
  - scope:
      path: "assets/pdf"
    values:
      pdf: true